name: Test Package

on: [push]
jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x, 16.13.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install python and others
        run: apt-get -y install node-gyp build-essential libssl-dev libffi-dev libblas3 libc6 liblapack3 gcc python3-dev
      - name: Install os dependecies
        run: apt-get update -y && apt-get install xserver-xorg-dev libxi-dev libxext-dev -y
      - name: Install dependencies
        run: npm install
      - run: npm test
